/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenizedVotes } from "./ITokenizedVotes";
export type { TokenizedBallot } from "./TokenizedBallot";
