/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITokenizedVotes__factory } from "./ITokenizedVotes__factory";
export { TokenizedBallot__factory } from "./TokenizedBallot__factory";
