/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenizedVotes,
  ITokenizedVotesInterface,
} from "../../../contracts/TokenizedBallot.sol/ITokenizedVotes";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "getPastVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "getVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITokenizedVotes__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenizedVotesInterface {
    return new utils.Interface(_abi) as ITokenizedVotesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenizedVotes {
    return new Contract(address, _abi, signerOrProvider) as ITokenizedVotes;
  }
}
